---

- name: "permissions for /etc/sawtooth"
  shell: "sudo chmod 777 -R /etc/sawtooth"
  become: yes

- name: "permissions for /home/sawtooth"
  shell: "sudo chmod 777 -R /home/sawtooth"
  become: yes

- name: "Set Role Key"
  shell: sudo sawset proposal create --key /etc/sawtooth/keys/validator.priv sawtooth.identity.allowed_keys=$(cat ~/.sawtooth/keys/monika.pub) --url http://172.16.1.99:8008
  args:
    creates: "~/.sawtooth/onchain-configured"
  become: yes
  become_user: dell

- name: "Create Transaction Access Policy"
  shell: echo sawtooth identity policy create -k ~/.sawtooth/keys/monika.priv --url http://172.16.1.99:8008 --wait 300 bcgt "DENY_KEY $(cat ~/.sawtooth/keys/monika.pub)" >/tmp/transactionpolicy.sh
  become: yes
  become_user: dell

- name: "Create Transaction Access Policy command"
  shell: sawtooth identity policy create -k ~/.sawtooth/keys/monika.priv --url http://172.16.1.99:8008 --wait 300 bcgt "DENY_KEY $(cat ~/.sawtooth/keys/monika.pub)"
  become: yes
  become_user: dell

- name: "Apply Transaction Access Policy"
  shell: sh /tmp/transactionpolicy.sh
  args:
    creates: "/home/dell/.sawtooth/onchain-configured"
  become: yes
  become_user: dell

- name: "Create Identity Role"
  shell: sudo sawtooth identity role create -k ~/.sawtooth/keys/monika.priv --url http://172.16.1.99:8008 transactor bcgt
  args:
    creates: "/home/dell/.sawtooth/onchain-configured"
  become: yes
  become_user: dell

- name: "permissions for onchain-configured"
  shell: "sudo chmod 777 /home/dell/.sawtooth/onchain-configured"
  become: yes

- name: "Create onchain-configured"
  file:
    path: /home/dell/.sawtooth/onchain-configured
    state: file 
    owner: root
    group: root
    mode: 0777
  become: yes


