---
- name: "Install Sawtooth-settings"
  apt:
    pkg=python3-sawtooth-settings
    state=present
    update_cache=true
  become: yes

- name: "Configure Sawtooth-validator"
  template:
    src: "settings.toml.j2"
    dest: "/etc/sawtooth/settings.toml"
    owner: root
    group: sawtooth
  become: yes
  notify:
    - start sawtooth-settings-tp
