---
- hosts: "{{ play_hosts }}"
  roles:
    - sawtooth-block-info
    - sawtooth-identity
    - "sawtooth-poet-{{ enclave }}"
    - sawtooth-rest-api
    - sawtooth-settings
    - sawtooth-validator
  become: yes

- hosts: "{{ play_hosts }}"
  roles:
    - "create-genesis-{{ enclave }}"
  become: yes

- hosts: "{{ play_hosts }}"
  roles:
    - restart-sawtooth-validator
  become: yes

